enum GroupType {
  basicGroup,
  superGroup,
}

enum ChatType {
  private,
  channel,
  group,
  bot,
}

enum ImageTitle {
  mulesport,
  atc,
  awaqi,
  ethiotel,
  fashintera,
  se2012,
  telebirr,
  tikvah,
  yenetube,
  user1,
  user2,
  user3,
  user4,
  user5,
  user6,
  user7,
  user8,
  user9,
  user10,
  user11,
  user12,
  user13,
  user14,
  user15,
  act1,
  act2,
  act3,
  act4,
  act5,
  sport1,
  sport2,
  sport3,
  sport4,
  sport5a,
  sport5b,
  tik1,
  tik2,
  tik3,
  tik4,
  tik5,
  userMessage1,
  userMessage2,
  userMessage3,
}

Map<ImageTitle, String> imageLink = {
  ImageTitle.mulesport: "assets/images/sender_images/mulesport.jpg",
  ImageTitle.atc: "assets/images/sender_images/atc.jpg",
  ImageTitle.awaqi: "assets/images/sender_images/awaqi.jpg",
  ImageTitle.ethiotel: "assets/images/sender_images/ethiotel.jpg",
  ImageTitle.fashintera: "assets/images/sender_images/fashintera.jpg",
  ImageTitle.se2012: "assets/images/sender_images/se2012.jpg",
  ImageTitle.telebirr: "assets/images/sender_images/telebirr.jpg",
  ImageTitle.tikvah: "assets/images/sender_images/tikvah.jpg",
  ImageTitle.yenetube: "assets/images/sender_images/yenetube.jpg",
  ImageTitle.user1: "assets/images/sender_images/user1m.jpeg",
  ImageTitle.user2: "assets/images/sender_images/user2f.jpeg",
  ImageTitle.user3: "assets/images/sender_images/user3m.jpeg",
  ImageTitle.user4: "assets/images/sender_images/user4f.jpeg",
  ImageTitle.user5: "assets/images/sender_images/user5f.jpeg",
  ImageTitle.user6: "assets/images/sender_images/user6m.jpeg",
  ImageTitle.user7: "assets/images/sender_images/user7f.jpeg",
  ImageTitle.user8: "assets/images/sender_images/user8f.jpeg",
  ImageTitle.user9: "assets/images/sender_images/user9f.jpeg",
  ImageTitle.user10: "assets/images/sender_images/user10m.jpeg",
  ImageTitle.user11: "assets/images/sender_images/user11m.jpeg",
  ImageTitle.user12: "assets/images/sender_images/user12f.jpeg",
  ImageTitle.user13: "assets/images/sender_images/user13m.jpeg",
  ImageTitle.user14: "assets/images/sender_images/user14.jpeg",
  ImageTitle.user15: "assets/images/sender_images/user15m.jpeg",
  ImageTitle.act1: "assets/images/message_images/atc1.jpg",
  ImageTitle.act2: "assets/images/message_images/atc2.jpg",
  ImageTitle.act3: "assets/images/message_images/atc3.jpg",
  ImageTitle.act4: "assets/images/message_images/atc4.jpg",
  ImageTitle.act5: "assets/images/message_images/atc5.jpg",
  ImageTitle.sport1: "assets/images/message_images/sport1.jpg",
  ImageTitle.sport2: "assets/images/message_images/sport2.jpg",
  ImageTitle.sport3: "assets/images/message_images/sport3.jpg",
  ImageTitle.sport4: "assets/images/message_images/sport4.jpg",
  ImageTitle.sport5a: "assets/images/message_images/sport5a.jpg",
  ImageTitle.sport5b: "assets/images/message_images/sport5b.jpg",
  ImageTitle.tik1: "assets/images/message_images/tik1.jpg",
  ImageTitle.tik2: "assets/images/message_images/tik2.jpg",
  ImageTitle.tik3: "assets/images/message_images/tik3.jpg",
  ImageTitle.tik4: "assets/images/message_images/tik4.jpg",
  ImageTitle.tik5: "assets/images/message_images/tik5.jpg",
  ImageTitle.userMessage1: "assets/images/message_images/user1.jpg",
  ImageTitle.userMessage2: "assets/images/message_images/user2.jpg",
  ImageTitle.userMessage3: "assets/images/message_images/user3.jpg",
};
